=== milomarten/vexle/src/main/resources/flagSchema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "flags",
  "title": "Flags",
  "description": "Flag definitions",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "countryCode": {
        "type": "string"
      },
      "name": {
        "type": "string"
      },
      "emoji": {
        "type": "string"
      },
      "colors": {
        "type": "array",
        "uniqueItems": true,
        "items": { "$ref": "#/$defs/colors" }
      },
      "charges": {
        "type": "array",
        "items": {
          "oneOf": [
            { "$ref": "#/$defs/charges" },
            {
              "type": "object",
              "properties": {
                "item": {
                  "$ref": "#/$defs/charges"
                },
                "count": {
                  "type": "number",
                  "minimum": 1
                }
              },
              "required": ["item", "count"]
            }
          ]
        }
      },
      "patterns": {
        "type": "array",
        "items": {
          "oneOf": [
            { "$ref": "#/$defs/patterns" },
            {
              "type": "object",
              "properties": {
                "item": {
                  "$ref": "#/$defs/patterns"
                },
                "count": {
                  "type": "number",
                  "minimum": 1
                }
              },
              "required": ["item", "count"]
            }
          ]
        }
      }
    },
    "required": ["countryCode", "name" ,"emoji", "colors", "patterns"]
  },
  "$defs": {
    "colors": {
      "enum": [
        "RED",
        "ORANGE",
        "YELLOW",
        "GREEN",
        "LIGHT_BLUE",
        "BLUE",
        "PURPLE",
        "PINK",
        "BLACK",
        "WHITE",
        "GRAY"
      ]
    },
    "charges": {
      "enum": [
        "STAR",
        "SUN",
        "MOON",
        "PLANT",
        "ANIMAL",
        "EMBLEM",
        "CROSS",
        "TERRITORY",
        "WEAPON",
        "ANOTHER_FLAG",
        "TEXT",
        "HUMAN",
        "BUILDING"
      ]
    },
    "patterns": {
      "enum": [
        "FIELD",
        "HORIZONTAL_STRIPE",
        "VERTICAL_STRIPE",
        "DIAGONAL_STRIPE",
        "CROSS",
        "DIAGONAL_CROSS",
        "GRID",
        "DIAGONAL_GRID",
        "CANTON",
        "BORDER",
        "TRIANGLE",
        "CIRCLE",
        "DIAMOND",
        "ORNAMENT"
      ]
    }
  }
}

=== milomarten/vexle/src/main/resources/flags.json
[
  {
    "countryCode": "AF",
    "name": "Afghanistan",
    "emoji": "\uD83C\uDDE6\uD83C\uDDEB",
    "colors": ["BLACK", "RED", "GREEN"],
    "charges": ["EMBLEM"],
    "patterns": [{"item": "VERTICAL_STRIPE", "count": 3}]
  },
  {
    "countryCode": "AX",
    "name": "Ã…land Islands",
    "emoji": "\uD83C\uDDE6\uD83C\uDDFD",
    "colors": ["BLUE", "RED", "YELLOW"],
    "patterns": ["FIELD", "CROSS"]
  },
  {
    "countryCode": "AL",
    "name": "Albania",
    "emoji": "\uD83C\uDDE6\uD83C\uDDF1",
    "colors": ["RED", "BLACK"],
    "patterns": ["FIELD"],
    "charges": ["ANIMAL"]
  },
  {
    "countryCode": "DZ",
    "name": "Algeria",
    "emoji": "\uD83C\uDDE9\uD83C\uDDFF",
    "colors": ["GREEN", "WHITE"],
    "patterns": [{"item": "VERTICAL_STRIPE", "count": 2}],
    "charges": ["MOON", "STAR"]
  },
  {
    "countryCode": "AS",
    "name": "American Samoa",
    "emoji": "\uD83C\uDDE6\uD83C\uDDF8",
    "colors": ["BLUE", "WHITE", "RED"],
    "patterns": ["TRIANGLE", "FIELD"],
    "charges": ["ANIMAL"]
  },
  {
    "countryCode": "AD",
    "name": "Andorra",
    "emoji": "\uD83C\uDDE6\uD83C\uDDE9",
    "colors": ["BLUE", "YELLOW", "RED"],
    "patterns": [{"item": "VERTICAL_STRIPE", "count": 3}],
    "charges": ["EMBLEM"]
  },
  {
    "countryCode": "AO",
    "name": "Angola",
    "emoji": "\uD83C\uDDE6\uD83C\uDDF4",
    "colors": ["RED", "BLACK", "YELLOW"],
    "patterns": [{"item": "HORIZONTAL_STRIPE", "count": 2}],
    "charges": ["STAR", "WEAPON"]
  },
  {
    "countryCode": "AI",
    "name": "Anguilla",
    "emoji": "\uD83C\uDDE6\uD83C\uDDEE",
    "colors": ["BLUE", "RED", "WHITE"],
    "patterns": ["FIELD", "CANTON"],
    "charges": ["ANOTHER_FLAG", "EMBLEM"]
  },
  {
    "countryCode": "AQ",
    "name": "Antarctica",
    "emoji": "\uD83C\uDDE6\uD83C\uDDF6",
    "colors": ["BLUE", "WHITE"],
    "patterns": ["FIELD"],
    "charges": ["TERRITORY"]
  },
  {
    "countryCode": "AG",
    "name": "Antigua and Barbuda",
    "emoji": "\uD83C\uDDE6\uD83C\uDDEC",
    "colors": ["RED", "WHITE", "BLUE", "BLACK", "YELLOW"],
    "charges": ["SUN"],
    "patterns": [{"item": "HORIZONTAL_STRIPE", "count": 3}, {"item": "TRIANGLE", "count": 2}]
  },
  {
    "countryCode": "AR",
    "name": "Argentina",
    "emoji": "\uD83C\uDDE6\uD83C\uDDF7",
    "colors": ["LIGHT_BLUE", "WHITE"],
    "charges": ["SUN"],
    "patterns": [{"item": "HORIZONTAL_STRIPE", "count": 3}]
  },
  {
    "countryCode": "AM",
    "name": "Armenia",
    "emoji": "\uD83C\uDDE6\uD83C\uDDF2",
    "colors": ["RED", "BLUE", "ORANGE"],
    "patterns": [{"item": "HORIZONTAL_STRIPE", "count": 3}]
  },
  {
    "countryCode": "AW",
    "name": "Aruba",
    "emoji": "\uD83C\uDDE6\uD83C\uDDFC",
    "colors": ["LIGHT_BLUE", "YELLOW", "RED"],
    "charges": ["STAR"],
    "patterns": ["FIELD", {"item": "HORIZONTAL_STRIPE", "count": 2}]
  },
  {
    "countryCode": "AU",
    "name": "Australia",
    "emoji": "\uD83C\uDDE6\uD83C\uDDFA",
    "colors": ["BLUE", "WHITE", "RED"],
    "charges": [{"item": "STAR", "count": 6}, "ANOTHER_FLAG"],
    "patterns": ["CANTON", "FIELD"]
  },
  {
    "countryCode": "AT",
    "name": "Austria",
    "emoji": "\uD83C\uDDE6\uD83C\uDDF9",
    "colors": ["RED", "WHITE"],
    "patterns": [{"item": "HORIZONTAL_STRIPE", "count": 3}]
  },
  {
    "countryCode": "AZ",
    "name": "Azerbaijan",
    "emoji": "\uD83C\uDDE6\uD83C\uDDFF",
    "colors": ["LIGHT_BLUE", "RED", "GREEN", "WHITE"],
    "patterns": [{"item": "HORIZONTAL_STRIPE", "count": 3}],
    "charges": ["MOON", "STAR"]
  },
  {
    "countryCode": "BS",
    "name": "The Bahamas",
    "emoji": "\uD83C\uDDE7\uD83C\uDDF8",
    "colors": ["LIGHT_BLUE", "YELLOW", "BLACK"],
    "patterns": [{"item": "HORIZONTAL_STRIPE", "count": 3}, "TRIANGLE"]
  },
  {
    "countryCode": "BH",
    "name": "Bahrain",
    "emoji": "\uD83C\uDDE7\uD83C\uDDED",
    "colors": ["RED", "WHITE"],
    "patterns": ["VERTICAL_STRIPE", "FIELD", {"item": "TRIANGLE", "count": 5}]
  },
  {
    "countryCode": "BD",
    "name": "Bangladesh",
    "emoji": "\uD83C\uDDE7\uD83C\uDDE9",
    "colors": ["GREEN", "RED"],
    "patterns": ["FIELD", "CIRCLE"]
  },
  {
    "countryCode": "BB",
    "name": "Barbados",
    "emoji": "\uD83C\uDDE7\uD83C\uDDE7",
    "colors": ["BLUE", "YELLOW", "BLACK"],
    "charges": ["WEAPON"],
    "patterns": [{"item": "VERTICAL_STRIPE", "count": 3}]
  },
  {
    "countryCode": "BY",
    "name": "Belarus",
    "emoji": "\uD83C\uDDE7\uD83C\uDDFE",
    "colors": ["RED", "WHITE", "GREEN"],
    "patterns": ["VERTICAL_STRIPE", "HORIZONTAL_STRIPE", "HORIZONTAL_STRIPE", "ORNAMENT"]
  },
  {
    "countryCode": "BE",
    "name": "Belgium",
    "emoji": "\uD83C\uDDE7\uD83C\uDDEA",
    "colors": ["BLACK", "YELLOW", "RED"],
    "patterns": [{"item": "VERTICAL_STRIPE", "count": 3}]
  },
  {
    "countryCode": "BZ",
    "name": "Belize",
    "emoji": "\uD83C\uDDE7\uD83C\uDDFF",
    "colors": ["RED", "BLUE"],
    "patterns": [{"item": "HORIZONTAL_STRIPE", "count": 2}, "FIELD"],
    "charges": ["EMBLEM"]
  },
  {
    "countryCode": "BJ",
    "name": "Benin",
    "emoji": "\uD83C\uDDE7\uD83C\uDDEF",
    "colors": ["RED", "GREEN", "YELLOW"],
    "patterns": ["HORIZONTAL_STRIPE", "HORIZONTAL_STRIPE", "VERTICAL_STRIPE"]
  },
  {
    "countryCode": "BM",
    "name": "Bermuda",
    "emoji": "\uD83C\uDDE7\uD83C\uDDF2",
    "colors": ["RED"],
    "patterns": ["CANTON"],
    "charges": ["EMBLEM", "ANOTHER_FLAG"]
  },
  {
    "countryCode": "BT",
    "name": "Bhutan",
    "emoji": "\uD83C\uDDE7\uD83C\uDDF9",
    "colors": ["YELLOW", "ORANGE"],
    "patterns": ["TRIANGLE", "TRIANGLE"],
    "charges": ["ANIMAL"]
  },
  {
    "countryCode": "BO",
    "name": "Bolivia",
    "emoji": "\uD83C\uDDE7\uD83C\uDDF4",
    "colors": ["RED", "YELLOW", "GREEN"],
    "charges": ["ANIMAL", "EMBLEM", "TEXT"],
    "patterns": [{"item": "HORIZONTAL_STRIPE", "count": 3}]
  },
  {
    "countryCode": "BA",
    "name": "Bosnia and Herzegovina",
    "emoji": "\uD83C\uDDE7\uD83C\uDDE6",
    "colors": ["BLUE", "YELLOW", "WHITE"],
    "patterns": ["TRIANGLE"],
    "charges": [{"item": "STAR", "count": 8}]
  },
  {
    "countryCode": "BW",
    "name": "Botswana",
    "emoji": "\uD83C\uDDE7\uD83C\uDDFC",
    "colors": ["LIGHT_BLUE", "WHITE", "BLACK"],
    "patterns": [{"item": "HORIZONTAL_STRIPE", "count": 5}]
  },
  {
    "countryCode": "BV",
    "name": "Bouvet Island",
    "emoji": "\uD83C\uDDE7\uD83C\uDDFB",
    "colors": ["BLUE", "WHITE", "RED"],
    "patterns": ["FIELD", "CROSS"]
  },
  {
    "countryCode": "BR",
    "name": "Brazil",
    "emoji": "\uD83C\uDDE7\uD83C\uDDF7",
    "colors": ["GREEN", "YELLOW", "BLUE"],
    "patterns": ["DIAMOND", "CIRCLE"],
    "charges": [{"item": "STAR", "count": 27}, "TEXT"]
  },
  {
    "countryCode": "IO",
    "name": "British Indian Ocean Territory",
    "emoji": "\uD83C\uDDEE\uD83C\uDDF4",
    "colors": ["BLUE", "WHITE"],
    "patterns": [{"item": "HORIZONTAL_STRIPE", "count": 13}, "CANTON"],
    "charges": ["ANOTHER_FLAG", "PLANT"]
  },
  {
    "countryCode": "BN",
    "name": "Brunei",
    "emoji": "\uD83C\uDDE7\uD83C\uDDF3",
    "colors": ["YELLOW", "WHITE", "BLACK"],
    "patterns": ["FIELD", "DIAGONAL_STRIPE", "DIAGONAL_STRIPE"],
    "charges": ["EMBLEM"]
  },
  {
    "countryCode": "BG",
    "name": "Bulgaria",
    "emoji": "\uD83C\uDDE7\uD83C\uDDEC",
    "colors": ["WHITE", "GREEN", "RED"],
    "patterns": [{"item": "HORIZONTAL_STRIPE", "count": 3}]
  },
  {
    "countryCode": "BF",
    "name": "Burkina Faso",
    "emoji": "\uD83C\uDDE7\uD83C\uDDEB",
    "colors": ["RED", "GREEN", "YELLOW"],
    "patterns": ["HORIZONTAL_STRIPE", "HORIZONTAL_STRIPE"],
    "charges": ["STAR"]
  },
  {
    "countryCode": "BI",
    "name": "Burundi",
    "emoji": "\uD83C\uDDE7\uD83C\uDDEE",
    "colors": ["RED", "GREEN", "WHITE"],
    "patterns": ["DIAGONAL_CROSS", "CIRCLE"],
    "charges": [{"item": "STAR", "count": 3}]
  },
  {
    "countryCode": "KH",
    "name": "Cambodia",
    "emoji": "\uD83C\uDDF0\uD83C\uDDED",
    "colors": ["RED", "BLUE", "WHITE"],
    "patterns": ["HORIZONTAL_STRIPE", "HORIZONTAL_STRIPE"],
    "charges": ["BUILDING"]
  },
  {
    "countryCode": "CM",
    "name": "Cameroon",
    "emoji": "\uD83C\uDDE8\uD83C\uDDF2",
    "colors": ["GREEN", "RED", "YELLOW"],
    "patterns": [{"item": "VERTICAL_STRIPE", "count": 3}],
    "charges": ["STAR"]
  },
  {
    "countryCode": "CA",
    "name": "Canada",
    "emoji": "\uD83C\uDDE8\uD83C\uDDE6",
    "colors": ["RED", "WHITE"],
    "patterns": [{"item": "VERTICAL_STRIPE", "count": 3}],
    "charges": ["PLANT"]
  }
]
